# Exercício:

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

## 01 – Usando o método np.random.normal(), gere valores de expressão gênica de um conjunto de 1.000 genes. Esse conjunto deve ter valores up e downregulated.

In [20]:
np.random.seed(42)
array_nml = np.random.normal(0,1,1000)
df_gns = pd.DataFrame(array_nml)
df_gns.columns = ["Up N Down regulation"]
df_gns.head()

   Up N Down regulation
0              0.496714
1             -0.138264
2              0.647689
3              1.523030
4             -0.234153

## 02 – Usando o método np.random.randint(), gere valores para o número de genes diferencialmente expressos em um conjunto de 1.000 pacientes. Esse conjunto deve ter valores up e downregulated.

Instancie um objeto da classe DataFrame, com os dados gerados nos dois exercícios.

In [21]:
np.random.seed(42)
array_pacientes = np.random.randint(0,23,1000)
df_pac = pd.DataFrame(array_pacientes)
df_pac.columns = ["Nº genes diferencialmente expressos"]
df_pac.head()

   Nº genes diferencialmente expressos
0                                    6
1                                   19
2                                   14
3                                   10
4                                    7

## 03 – Categorize em grupos de 6 os dados contidos na DataFrame anterior, segundo critérios escolhidos por você. Explique os critérios.

R.:

In [ ]:
# Criando nova coluna
df_pac["Amostras"] = None

# Categorizando em 6 grupos
for x in range(len(df_pac["Nº genes diferencialmente expressos"])):
    if x <12:
        if df_pac.iloc[x,0]<4:
            df_pac.iloc[x,1] = "Amostra 1"
        elif 4<=df_pac.iloc[x,0]<8:
            df_pac.iloc[x,1] = "Amostra 2"
        else:
            df_pac.iloc[x,1] = "Amostra 3"
    else:
        if 12<=df_pac.iloc[x,0]<16:
            df_pac.iloc[x,1] = "Amostra 4"
        elif 16<=df_pac.iloc[x,0]<20:
            df_pac.iloc[x,1] = "Amostra 5"
        else:
            df_pac.iloc[x,1] = "Amostra 6"
display(df_pac.head())
display(df_pac.tail())

   Nº genes diferencialmente expressos   Amostras
0                                    6  Amostra 2
1                                   19  Amostra 3
2                                   14  Amostra 3
3                                   10  Amostra 3
4                                    7  Amostra 2

     Nº genes diferencialmente expressos   Amostras
995                                   13  Amostra 4
996                                   20  Amostra 6
997                                   10  Amostra 6
998                                    8  Amostra 6
999                                    1  Amostra 6

O critério escolhido foi dividir os grupos em 6 partes com tamanhos de intervalos iguais. Uma vez que os números inteiros do df_pac varia de 0 a 23 (24 números possíveis), dividindo em 6 partes resulta em 6 grupos de intervalo igual a 4 (0 a 3; 4 a 7; 8 a 11; 12 a 15; 16 a 19; e 20 a 24). Neste caso, não cria um peso dos intervalos e permite distribuir mais egualitariamente os valores.

## 04 – Defina uma função em Python que receba uma pd.Series contendo uma variável quantitativa e retorne uma DataFrame contendo a tabela de frequência.

Obtenha a tabela de frequência das variáveis criadas nos exercícios 1 e 2.

## 05 – Gere os gráficos de barras e linhas para as frequências em cada umas das variáveis.

### Expressão

### Número

## 06 – Gere os histogramas para as variáveis obtidas nos exercícios 1 e 2.

## 07 – Gere um gráfico de dispersão para as variáveis obtidas nos exercícios 1 e 2.

## 08 – Gere o mesmo gráfico do exercício 06, porém, categorizado.

## 09 – Gere o mesmo gráfico do exercício 07, porém, categorizado.

## 10 – Indique o tipo da variável:

- Discreta
- Contínua
- Ordinal
- Nominal

| Variável | Valor |
| :--- | :---: |
| # de células positivas||
| % de células positivas||
| Faixa de pH||
| Valor de pH||
| mol/L||
| UFC||
| D.O.||
| Grupo Sanguíneo||
| Sorologia||