In [2]:
!pip install biopython

Collecting biopython
  Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 60.6 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.87

In [3]:
import pandas as pd
import numpy as np
from Bio import Entrez
import time
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Importando o arquivo
df_genes = pd.read_csv('df_genes.csv', index_col='Unnamed: 0')
df_genes

,Número de Caracteres,Dois Primeiros Caracteres,Quantidade de 'a's,Presença de Caracteres 'hu'
SRY,3,SR,0,False
Cetn-1,6,Ce,0,False
PFR2,4,PF,0,False
HER2,4,HE,0,False
GFP,3,GF,0,False

In [5]:
# Criando as colunas para acessar os arquivos FASTA dos genes por API
df_genes['id_entrez'] = [
    "NM_003140.3",
    "NM_004066.3",
    "XM_842234.1",
    "NM_004448.4",
    "XM_067079949.1"
]

df_genes['id_protein'] = [
    "NP_003131.1",
    "NP_004057.1",
    "XP_847327.1",
    "NP_004439.2",
    "XP_066936050.1"
]

df_genes

# Obs.: Para o gene PFR2 e GFP não havia MANE select. Como nos exercícios vai precisar apenas do
# id_protein, colocou o transcript accession equivalente para esses dois genes.

,Número de Caracteres,Dois Primeiros Caracteres,Quantidade de 'a's,Presença de Caracteres 'hu',id_entrez,id_protein
SRY,3,SR,0,False,NM_003140.3,NP_003131.1
Cetn-1,6,Ce,0,False,NM_004066.3,NP_004057.1
PFR2,4,PF,0,False,XM_842234.1,XP_847327.1
HER2,4,HE,0,False,NM_004448.4,NP_004439.2
GFP,3,GF,0,False,XM_067079949.1,XP_066936050.1

In [7]:
def salvar_fasta_gene(id_protein: str, nome_gene: str) -> None:
    '''
        Salva a sequência de um gene em formato FASTA.
            Args:
                id_protein (str): ID do gene no GenBank.
                nome_gene (str): Nome do gene para salvar o arquivo.
            Returns:
                None
    '''
    # Necessário informar seu email
    Entrez.email = "rafaeluveiga@gmail.com"

    # Busca a sequência (ex: um ID do GenBank)
    handle = Entrez.efetch(db="protein", id=id_protein, rettype="fasta", retmode="text")
    record = handle.read()
    handle.close()

    # Salva o arquivo
    with open(f"./{nome_gene}.fasta", "w") as f:
        fasta = f.write(record)

    return None

In [8]:
for index in df_genes.index:
    id_gene = df_genes.loc[index, "id_protein"]
    nome_gene = index
    salvar_fasta_gene(nome_gene=nome_gene, id_protein=id_gene)
    time.sleep(10)  # Para evitar sobrecarga no servidor do NCBI
    print(nome_gene, id_gene)

SRY NP_003131.1
Cetn-1 NP_004057.1
PFR2 XP_847327.1
HER2 NP_004439.2
GFP XP_066936050.1